POST http://pizza.com/api/order/add
Content-Type: application/json

{
    "orderList": [
        3
    ],
    "totalPrice": 12.45,
    "name": "IRINA GRIN",
    "phone": "89532726991",
    "address": "Romana Bryanskogo"
}

###

POST http://pizza.com/api/pizza/list
Content-Type: application/json

###

POST http://pizza.com/api/user/logout
Content-Type: application/json

###

POST http://pizza.com/api/user/login
Content-Type: application/json

###

POST http://pizza.com/api/user/info
Content-Type: application/json

###
